#!/usr/bin/env bash
# A Bash script that transfers a file from our client to a server

file=$1
ip=$2
user=$3
path_key=$4

if [ $# -lt 4 ]; then
	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit
else
	scp -i "$path_key" -o StrictHostKeyChecking=no "$file" "$user@$ip:~"
fi;
