#!/usr/bin/env bash
# Install a web server to serve webpages on requests.

# update system and dependencies.
sudo apt update -y

# Install nginx web server.
sudo apt install -y nginx

# storing Hello World in the nginx default html file
# so when curl is used it return Hello World instead of the default
# ngnix page
echo 'Hello World!' | sudo tee /var/www/html/index.nginx-debian.html

# Restarting nginx to aapply all configurations
sudo service nginx restart
