#!/usr/bin/env bash
# update system and dependencies.
sudo apt update -y
# Install HAproxy
sudo apt install haproxy -y

sudo chown -R "$USER" /etc/haproxy

# configuration for HAproxy
if ! grep 'frontend my_frontend' /etc/haproxy/haproxy.cfg; then
        echo "frontend my_frontend
        bind *:80
        default_backend my_backend
        " >> /etc/haproxy/haproxy.cfg
        echo "backend my_backend
        balance roundrobin
        server 271786-web-01 100.26.164.241:80 check
        server 271786-web-02 34.229.49.155:80 check" >> /etc/haproxy/haproxy.cfg
fi
# Restarting HAproxy via an init script
sudo /etc/init.d/haproxy restart
