#!/usr/bin/env bash
# debugging the container

sed -i 's/listen 8080 default_server;/listen 80 default_server;/' /etc/nginx/sites-available/default
sed -i 's/listen \[::\]:8080 default_server ipv6only=on;/listen [::]:80 default_server ipv6only=on;/' /etc/nginx/sites-available/default
sudo rm /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/
sudo service nginx restart
