#!/usr/bin/env bash
# script the runs nginx as nginx user not default root
sed -i 's/#user www-data;/user nginx;/' /etc/nginx/nginx.conf
sed -i 's/80/8080/' /etc/nginx/sites-available/default
sudo service nginx restart
